# Generated by Django 5.2.5 on 2025-11-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='group_id',
            field=models.JSONField(blank=True, null=True, verbose_name='group_id'),
        ),
        migrations.AddField(
            model_name='notification',
            name='notify_type',
            field=models.CharField(choices=[('Invite', 'Invite'), ('Task status update', 'Task status update')], default=1, verbose_name='message type'),
            preserve_default=False,
        ),
    ]
