# Generated by Django 5.2.5 on 2025-11-15 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_notification_group_id_notification_notify_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='group_id',
            new_name='data',
        ),
    ]
