# Generated by Django 5.2.5 on 2025-08-25 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'група', 'verbose_name_plural': 'групы'},
        ),
        migrations.AlterModelTable(
            name='group',
            table='group',
        ),
    ]
