# Generated by Django 5.2.5 on 2025-11-16 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_group_id_notification_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_event', models.CharField(max_length=200, verbose_name='triggered event')),
                ('event_type', models.CharField(choices=[('Add member', 'Add member'), ('Kicked member', 'Kicked Member')], verbose_name='event type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='users.group', verbose_name='logs')),
            ],
            options={
                'verbose_name': 'GroupLog',
                'verbose_name_plural': 'GroupLogs',
                'db_table': 'group_logs',
            },
        ),
    ]
