# Generated by Django 5.2.5 on 2025-11-18 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_grouplogs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grouplogs',
            old_name='trigger_event',
            new_name='event',
        ),
        migrations.AddField(
            model_name='grouplogs',
            name='anchor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_anchor', to=settings.AUTH_USER_MODEL, verbose_name='event_triggered'),
        ),
        migrations.AddField(
            model_name='grouplogs',
            name='data',
            field=models.JSONField(default=dict, null=True, verbose_name='log_data'),
        ),
        migrations.AlterField(
            model_name='grouplogs',
            name='event_type',
            field=models.CharField(choices=[('Add member', 'Add member'), ('Kicked member', 'Kicked Member'), ('Change settings', 'Change settings'), ('Invite member', 'Invite member')], verbose_name='event type'),
        ),
    ]
