# Generated by Django 5.2.5 on 2025-11-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_trigger_event_grouplogs_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouplogs',
            name='event_type',
            field=models.CharField(choices=[('Add member', 'Add member'), ('Kicked member', 'Kicked Member'), ('Change settings', 'Change settings'), ('Invite member', 'Invite member'), ('Invite deflected', 'Invite deflected')], verbose_name='event type'),
        ),
    ]
