# Generated by Django 5.2.5 on 2025-09-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_group_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_profile',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='image_profile'),
        ),
    ]
