# Generated by Django 5.2.5 on 2025-12-23 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_grouplogs_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notify_type',
            field=models.CharField(choices=[('invite', 'invite'), ('task status update', 'task status update')], verbose_name='message type'),
        ),
    ]
