# Generated by Django 5.2.5 on 2026-06-26 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_notification_notify_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notify_type',
            field=models.CharField(choices=[('invite', 'invite'), ('task', 'task')], verbose_name='message type'),
        ),
    ]
