# Generated by Django 5.2.5 on 2025-08-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=130, verbose_name='project_title')),
                ('description', models.CharField(max_length=500, verbose_name='project_description')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130, verbose_name='task_name')),
                ('description', models.CharField(max_length=1000, verbose_name='task_description')),
                ('deadline', models.DateTimeField(verbose_name='task_deadline')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
