# Generated by Django 5.2.5 on 2025-12-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_rename_url_taskimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcomment',
            name='answer_to',
            field=models.JSONField(default={'id': None, 'text': None}, verbose_name='reply_message'),
        ),
    ]
