# Generated by Django 5.2.5 on 2025-08-26 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_project_group'),
        ('users', '0004_alter_group_options_alter_group_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='users.group', verbose_name='project_group'),
            preserve_default=False,
        ),
    ]
