# Generated by Django 5.2.5 on 2025-12-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_taskcomment_answer_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcomment',
            name='answer_to',
            field=models.JSONField(default=list, verbose_name='reply_message'),
        ),
    ]
