# Generated by Django 5.2.5 on 2025-09-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_alter_task_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('NS', 'No Status'), ('BS', 'Active task'), ('US', 'Urgent task')], default=1, verbose_name='task_status'),
            preserve_default=False,
        ),
    ]
