# Generated by Django 5.2.5 on 2025-10-14 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_task_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='task.task', verbose_name='chat')),
            ],
            options={
                'verbose_name': 'Task Chat',
                'verbose_name_plural': 'Task Chats',
                'db_table': 'chat_task',
            },
        ),
        migrations.CreateModel(
            name='TaskChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=700, verbose_name='text_message')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.taskchat', verbose_name='messages')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'db_table': 'task_chat_message',
            },
        ),
    ]
