# Generated by Django 5.2.5 on 2026-01-12 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_task_performers_taskperformsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskperformsession',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performs_sessions', to='task.task', verbose_name='session task'),
        ),
    ]
