# Generated by Django 5.2.5 on 2026-01-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_alter_taskperformsession_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskperformsession',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
