# Generated by Django 5.2.5 on 2026-02-10 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_taskperformsession_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskperformsession',
            name='duration',
            field=models.DurationField(verbose_name='session duration'),
        ),
    ]
