# Generated by Django 5.2.5 on 2026-02-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_activetask'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskperformsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
