# Generated by Django 5.2.5 on 2026-02-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0012_taskperformsession_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcomment',
            name='text',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='text_message'),
        ),
    ]
