# Generated by Django 5.2.5 on 2026-04-22 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0013_alter_taskcomment_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stratagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='stratagem name')),
                ('action', models.CharField(choices=[('OT', 'Open task'), ('OP', 'Open project'), ('OG', 'Open group'), ('OURL', 'Open url')])),
                ('url', models.URLField(verbose_name='url redirect')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(verbose_name='stratagem data')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stratagems', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
