# Generated by Django 5.2.5 on 2026-04-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0014_stratagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='stratagem',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
