# Generated by Django 5.2.5 on 2026-04-23 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0015_stratagem_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='stratagem',
            name='combination',
            field=models.JSONField(default=list),
        ),
    ]
