# Generated by Django 5.2.5 on 2026-04-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0016_stratagem_combination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stratagem',
            name='data',
            field=models.JSONField(blank=True, null=True, verbose_name='stratagem data'),
        ),
    ]
