# Generated by Django 5.2.5 on 2026-06-26 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0019_alter_task_performers'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=255)),
                ('priority', models.CharField(choices=[('low', 'Low priority'), ('Normal', 'Normal priority'), ('High', 'High priority')], max_length=155, verbose_name='subtask priority')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
