# Generated by Django 5.2.5 on 2026-08-16 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0020_subtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskimage',
            name='message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_image', to='task.taskcomment'),
        ),
    ]
