# Generated by Django 5.2.5 on 2026-09-01 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0021_alter_taskimage_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
