from .settings import *
from decouple import config

MAIN_ORIGIN = config("MAIN_ORIGIN", None)

if MAIN_ORIGIN:
    ALLOWED_HOSTS += [MAIN_ORIGIN]

DEBUG = False


SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SESSION_COOKIE_SECURE = True  
CSRF_COOKIE_SECURE = True     
SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SAMESITE = 'None' 
CSRF_COOKIE_SAMESITE = 'None'   


SECURE_HSTS_SECONDS = 3600  # 1 час
SECURE_HSTS_INCLUDE_SUBDOMAINS = False
SECURE_HSTS_PRELOAD = False

CSRF_COOKIE_HTTPONLY = False
CSRF_HEADER_NAME = 'HTTP_X_CSRFTOKEN'
CSRF_COOKIE_NAME = 'csrftoken'
SESSION_COOKIE_NAME = 'sessionid'